---
# Spring Boot defaults to 8080
server:
  port: 8080

example:
  message: Message from local application.yml

---
spring:
  profiles: zone-jp

example:
  message: Message from local application.yml - zone-jp

---
spring:
  profiles: zone-us

example:
  message: Message from local application.yml - zone-us
