info:
  component: Turbine Application

server:
  port: ${PORT:8989}

spring:
  application:
    name: turbine-application

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  port: 8990

eureka:
  client:
    serviceUrl:
      # Generally provide comma separated list of clients
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

turbine:
  clusterNameExpression: new String("default")
  appConfig: EXAMPLE,EXAMPLE-CLIENT
  combineHostPort: true
