---
#spring:
#  profiles: default
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      # Generally provide comma separated list of clients
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

zuul:
  prefix: /api
  ignored-services: '*' # Blacklist all. Otherwise specify services
  routes:
    example:
      path: /example/**
      #stripPrefix: true
      serviceId: example
#    service-b:
#      path: /custom-service-b/**
#      stripPrefix: true
#      serviceId: service-b:
