---
# This default profile is used when running a single instance completely standalone:
server:
  port: 8761

spring:
  profiles: default

eureka:
  server:
    enableSelfPreservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
